### PR TITLE
Update is-number and fill-range to version 4.0

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Note that if we now update fill-range with the latest `to-regex-range`, we'll need to do a major bump on fill-range again. I know I said this before, but this will only create more duplicates in the dependency tree, and continue to create an endless loop of bumps with no payoff.

**Comment by jonschlinkert** [comment]
Also, going forward, if you do a PR with a major bump, please check for a changelog as well and (if one exists) please add a major version to the release history with a note of the change. thanks

**Comment by realityking** [comment]
Right thus this comment https://github.com/jonschlinkert/fill-range/pull/7#issuecomment-340976721

That was me not paying attention, sorry about that. I won't be updating `fill-range` in this repo as it's only a dev dependency.

+1 on the changelog. I'll go through my open PRs and add any that are missing.

**Comment by jonschlinkert** [comment]
> +1 on the changelog. I'll go through my open PRs and add any that are missing.

thanks, I appreciate it

**Comment by realityking** [comment]
Looks like none of the repos I have open PRs on have one :)

**Comment by jonschlinkert** [comment]
> Right thus this comment jonschlinkert/fill-range#7 (comment)

Sorry, I think you might be missing my point. 

As an example, fill-range has 27 dependents. Any of those might be elsewhere in your dependency tree, in which case there will now be duplicates of fill-range in your dependency tree (one again) until all of those libraries also update their versions of fill-range to the latest. By the time that happens, it's possible if not likely that this library will have changes again. 

Even if those libraries aren't in your dependency tree, we're potentially causing duplicates for other libraries that do depend on those libs. To you, this might not matter, since you're accomplishing your goal for yourself, but to me, it matters because we're causing unnecessary work for other devs that use fill-range.

My example was about fill-range, but the same thing obviously applies to all libs. At least one of the libs you did PRs on has hundreds of dependents, and some of those dependents are libs like yarn, jest, nyc, etc. Which means more duplicates for their users.

**Comment by realityking** [comment]
I indeed missed your point. I thought it was about causing a two majors in short succession. 

As mentioned before my concern are those dependencies descendant of micromatch in the hope of getting a clean tree when/if es128/anymatch#22 happens. Right now micromatch pulls in 4 different versions of kind-of alone.

You obviously have a different perspective then I do (I'm a greenkeeper fan) and your approach of bumping the major when updating dependencies reflects that.

In the end these packages are your show, if you'd rather have me stop this I'm happy to do so.

**Comment by jonschlinkert** [comment]
> if you'd rather have me stop this I'm happy to do so.

not at all, it's appreciated and totally up to you. I explained my point, you are the best judge of what you need for your projects, and I'm happy to help.

**Pull request merged**
